name: discord_bot
version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: DiscordBot
    env_file:
      - .env
    depends_on:
      - postgreSQL
  postgreSQL:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: