name: discord_bot
version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: DiscordBot
    env_file:
      - .env
    volumes:
      - database:/app/youtube_reminder_data

volumes:
  database: