apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bot
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: "{{ .Values.bot.image }}"
          imagePullPolicy: {{ .Values.bot.pullPolicy }}
          envFrom:
            {{- range .Values.bot.secretNames }}
            - secretRef:
                name: {{ . }}
            {{- end }}
