bot:
  image: discord-bot:latest
  pullPolicy: IfNotPresent
  secretNames: 
    - discord-bot-secrets
    - postgresql-secrets

postgresql:
  image: postgres:latest
  pullPolicy: IfNotPresent
  secretName: postgresql-secrets
  persistence:
    enabled: false
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 8Gi